#!/bin/bash

# custom AppRun for Prism AppImage

# path of the extracted AppRun
HERE="$(dirname "$(readlink -f "${0}")")"
PRISM_PATH=/usr/bin/prism
PRISM_BIN_HERE=$HERE/usr/bin/prism
PRISM_SHARE_HERE=$HERE/usr/share/prism
PRISM_SESSION_DIR=$HERE/usr/libexec/prism
export PRISM_SESSION_DIR

# Set APPDIR when running directly from the AppDir:
if [ -z "$APPDIR" ]; then
    ARGV0="AppRun"
fi

cd "$HERE" || exit 1

function help() {
echo "
 ------------------------------
   Prism AppImage package.
 ------------------------------

 prism.AppImage options
 ------------------------

 Usage:  $ARGV0  --help, -h
 ------            # This message

         $ARGV0  --install, -i
                   # Install input rules prism.service files. Restart required.

         $ARGV0  --remove, -r
                   # Remove input rules prism.service files.

         $ARGV0  --appimage-help
                   # Show available AppImage options

 prism options
 ----------------
"
# print prism binary help, replacing the prism command in usage statement
"$PRISM_BIN_HERE" --help | sed -e "s#$PRISM_BIN_HERE#$ARGV0#g"
}

function install() {
  # user input rules
  # shellcheck disable=SC2002
  cat "$PRISM_SHARE_HERE/udev/rules.d/60-prism.rules" | sudo tee /etc/udev/rules.d/60-prism.rules
  cat "$PRISM_SHARE_HERE/modules-load.d/60-prism.conf" | sudo tee /etc/modules-load.d/60-prism.conf
  sudo modprobe uhid
  sudo udevadm control --reload-rules
  sudo udevadm trigger --property-match=DEVNAME=/dev/uinput
  sudo udevadm trigger --property-match=DEVNAME=/dev/uhid

  # prism service
  mkdir -p ~/.config/systemd/user
  cp -r "$PRISM_SHARE_HERE/systemd/user/" ~/.config/systemd/
  # patch service executable path
  sed -i -e "s#$PRISM_PATH#$(readlink -f $ARGV0)#g" ~/.config/systemd/user/app-dev.lizardbyte.app.Prism.service

  # setcap
  sudo setcap cap_sys_admin,cap_sys_nice+p "$(readlink -f "$PRISM_BIN_HERE")"
}

function remove() {
  # remove input rules
  sudo rm -f /etc/udev/rules.d/60-prism.rules

  # remove uhid module loading config
  sudo rm -f /etc/modules-load.d/60-prism.conf

  # remove service
  sudo rm -f ~/.config/systemd/user/app-dev.lizardbyte.app.Prism.service
}

# process arguments
if [ "x$1" == "xhelp" ] || [ "x$1" == "x--help" ] || [ "x$1" == "x-h" ] ; then
    help
    exit $?
fi

if [ "x$1" == "xinstall" ] || [ "x$1" == "x--install" ] || [ "x$1" == "x-i" ] ; then
    install
    exit $?
fi

if [ "x$1" == "xremove" ] || [ "x$1" == "x--remove" ] || [ "x$1" == "x-r" ] ; then
    remove
    exit $?
fi

if [ "x$1" == "x--internal" ]; then
    if [ "x${2:-}" != "xsession-cleanup" ] || [ "$#" -ne 2 ]; then
        echo "Unknown internal component" >&2
        exit 64
    fi
    exec "$PRISM_SESSION_DIR/prism-session-cleanup.sh"
fi

# create config directory if it doesn't exist
# https://github.com/LizardByte/Sunshine/issues/324
mkdir -p ~/.config/prism

# run prism
"$PRISM_BIN_HERE" "$@"
