---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "30 2 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "America/New_York"
    groups:
      npm-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:15"
      timezone: "America/New_York"
    groups:
      actions-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
      timezone: "America/New_York"
    groups:
      docker-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:45"
      timezone: "America/New_York"
    groups:
      python-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
