# Sonar project analysis properties overrides
# Automatic analysis ignores this file, and uses .sonarcloud.properties instead

sonar.projectKey=atgehrhardt_Prism

sonar.exclusions=third-party/**, packaging/linux/flatpak/deps/**

# sonar.cfamily.reportingCppStandardOverride=c++23
